name: First flow

on: workflow_dispatch
jobs: 
   first_job:
      runs-on:  ubuntu-latest
      steps:
       - name: print greeting
         run: echo "hello Sir!"
       - name: print naah
         run: echo "Yes good bye"
      
